Update various.json
undera/jmeter-plugins pull request #665
Opened 2024-08-20 18:11 UTC by DanilGolikov

Created [JmeterNamesTemplater](https://github.com/DanilGolikov/JmeterNamesTemplater) that allows you to rename items according to the config file

2024-08-20 19:19 UTC, undera requested changes

2024-08-20 19:19 UTC, undera commented on site/dat/repo/various.json
> +      "com.example.jmeter.plugin.gui.RenameElementsMenuCreator",
`com.example.jmeter.plugin` does not look like a good namespace for plugin. Can you come up with something more distinctive? Something more author-specific.
Should be a simple refactoring.

2024-08-20 19:19 UTC, undera commented on site/dat/repo/various.json
> +    "helpUrl": "https://github.com/DanilGolikov/JmeterNamesTemplater/blob/master/README.md",
`https://github.com/DanilGolikov/Custom_jmeter_functions` should be simpler and sufficient URL here.

Also I'd work on that page for better presentation, titles and help document structure. Up to you, though.

2024-08-21 07:58 UTC, DanilGolikov commented
Hi! I corrected the namespace, I didn't pay attention to the fact that it looks stupid xD before.
I also added another plugin (CustomJmeterFunctions), with your recommendations

2024-08-23 09:41 UTC, DanilGolikov reviewed
.

2024-08-25 09:01 UTC, undera commented on site/dat/repo/various.json
> +    "name": "Custom Jmeter Functions",
There is existing plugin with this name, you need to choose a different name. Preferably a name that explains what kind of functions are inside. Like "Functions for strings templating" or like that.
Don't forget to change the ID of plugin, and also the description of it should explain more what is inside.

2024-08-25 09:41 UTC, undera commented
Please make the title of PR to reflect what is inside. Look at other PRs to get the idea

2024-08-25 09:42 UTC, undera requested changes
Please address my comments

2024-08-25 12:22 UTC, undera commented
Looks like your JSON violate descriptor schema: https://github.com/undera/jmeter-plugins/actions/runs/10546658418/job/29218873882?pr=665

2024-08-25 12:56 UTC, undera commented
Looks good now

2024-08-25 12:56 UTC, merged